const Unions = [['«Ермак»', {rank: 'Председатель', fio: 'Сурженко Кирилл Романович ', link: '209342469', photo: require('../assets/surzhenko.jpg'), address: 'г. Красноярск, проспект Мира, 82',
                telefon: '+7 983 403 33 05', vk: 'https://vk.com/vpksibguermak', logo: require('../assets/ermak.png')}],
                ['Союз студентов', {rank: 'Председатель', fio: 'Плескач Дмитрий Иванович', link: '140607546', photo: require('../assets/pleskach.jpg'), address: 'г. Красноярск, проспект им. газеты Красноярский рабочий, 31, Корпус "А", каб. 409/2',
                telefon: '+7 923 757 87 83', vk: 'https://vk.com/vk_souz', logo: require('../assets/souz.jpg')}],
                ['Студенческие отряды', {rank: 'Руководитель штаба студенческих отрядов', fio: 'Немцев Дмитрий Эдуардович', link: '194906356', photo: require('../assets/nemcev.png'), address: 'г. Красноярск, проспект им. газеты Красноярский рабочий, 56, Корпус "Д", каб. 108',
                telefon: '+7 999 441 04 39', vk: 'https://vk.com/so_sibgu', logo: require('../assets/otryad.png')}],
                ['«Лис»', {rank: 'Председатель', fio: 'Ионцева Светлана Михайловна', link: '135372125', photo: require('../assets/ionceva.jpg'), address: 'г. Красноярск, проспект Мира, 82, Корпус "Гл", каб. 012',
                telefon: '+7 983 293 32 04', vk: 'https://vk.com/leaguelis', logo: require('../assets/lis.png')}],
                ['МСК', {rank: 'Председатель', fio: 'Заречанский Андрей Владимирович', link: '413772221', photo: require('../assets/zarechanskiy.png'), address: 'г. Красноярск, проспект им. газеты Красноярский рабочий, 31, Корпус "П", каб. 108',
                telefon: '+7 913 513 62 82', vk: 'https://vk.com/isc.sibsu', logo: require('../assets/international.png')}],
                ['КСЛ', {rank: 'Председатель', fio: 'Шумбасов Артур Максимович', link: '47853963', photo: require('../assets/shumbasov.png'), address: 'г. Красноярск, проспект им. газеты Красноярский рабочий, 31, Корпус "Л", каб 314',
                telefon: '+7 905 974 63 64', vk: 'https://vk.com/sibsu_tournament', logo: require('../assets/cybersport.jpg')}],
                ['СНО', {rank: 'Председатель', fio: 'Бойко Дмитрий Александрович', link: '319295137', photo: require('../assets/boyko.png'), address: 'г. Красноярск, проспект им. газеты Красноярский рабочий, 31, Корпус "Л", каб. 1101',
                telefon: '+7 923 361 00 80', vk: 'https://vk.com/sibsu_sno', logo: require('../assets/science.png')}],
                ['Волонтерский центр', {pred: 'Председатель', fio: 'Михайлова Лэйла Алексеевна', link: '221093252', photo: require('../assets/mihaylova.png'), address: 'г. Красноярск, проспект им. газеты Красноярский рабочий, 31, Корпус "Н"',
                telefon: '+7 913 527 48 78', vk: 'https://vk.com/vcsibsu', logo: require('../assets/volunteer.png')}],
                ['Профком', {rank: 'Председатель', fio: 'Кампова Ирина Юрьевна', link: '71111410', photo: require('../assets/kampova.png'), address: 'г. Красноярск, проспект Мира, 82, Корпус "Гл", каб. 216',
                telefon: '+7 391 266 04 09', vk: 'https://vk.com/profsouz_sibsu', logo: require('../assets/profkom.png')}],
                ['аэроСМИ', {rank: 'Руководитель', fio: 'Бакулин Роман Владимирович', link: '100491429', photo: require('../assets/bakulin.png'), address: 'г. Красноярск, проспект им. газеты Красноярский рабочий, 31, Корпус "Л", каб. 905',
                telefon: '+7 913 507 02 39', vk: 'https://vk.com/aerosmi', logo: require('../assets/aerososi.png')}],
                ['«Сириус»', {rank: 'Председатель', fio: 'Моисеева Ольга Сергеевна', link: '184811003', photo: require('../assets/moiseeva.png'), address: 'г. Красноярск, проспект им. газеты Красноярский рабочий, 31, Корпус "Л", каб. 314',
                telefon: '+7 983 503 30 52', vk: 'https://vk.com/sirius_sibsu', logo: require('../assets/sirius.png')}],
                ['«ИнсайТ»', {rank: 'Социально-психологический центр "Инсайт"СибГУ им.М.Ф.Решетнева — объединение профессиональных психологов.', fio: 'Работает бесплатно для студентов и работников СибГУ.', link: '', photo: require('../assets/insight.jpg'), address: 'г. Красноярск, проспект Мира, 82, Корпус "Цл", каб. 209',
                telefon: '+7 391 222 73 44', vk: 'https://vk.com/spc.insight', logo: require('../assets/insight.jpg')}]]

export default Unions